spring:
  application:
    name: rule-engine
  rabbitmq:
    host: 133.186.221.92
    port: '5672'
    username: user
    password: user
  redis:
    host: 133.186.244.96
    port: 6379
    password: '*N2vya7H@muDTwdNMR!'
    database: 13

influxdb:
  token: noC68n9KNe6HJd20B9HFaRf68SuYV2lLVdGuuj1aFZb9xaJ4wlkL7Wxf02_ajEVxgw8PupjrTAwQo7kX6K65fA==
  url: http://133.186.217.132:8086
  org: TXT
  bucket: TxT-iot

server:
  port: '9897'

rabbitmq:
  exchange:
    name: txt.device.control
    sensor:
      name: txt.sensor.data
  predict:
    routing:
      key: txt.predict
  bindings:
    - queueName: aircleanerQueue
      routingKey: aircleanerRouterKey
    - queueName: lightQueue
      routingKey: lightRouterKey
    - queueName: airconditionerQueue
      routingKey: airconditionerRouterKey
    - queueName: occupancyQueue
      routingKey: occupancyRouterKey
    - queueName: batteryQueue
      routingKey: batteryRouterKey
    - queueName: predictQueue
      routingKey: predictRouterKey

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@133.186.220.58:8761/eureka,http://admin:1234@133.186.220.58:8762/eureka
