spring:
  rabbitmq:
    password: user
    host: 133.186.221.92
    port: '5672'
    username: user

influxdb:
  bucket: TxT-iot
  token: noC68n9KNe6HJd20B9HFaRf68SuYV2lLVdGuuj1aFZb9xaJ4wlkL7Wxf02_ajEVxgw8PupjrTAwQo7kX6K65fA==
  url: http://133.186.217.132:8086
  org: TXT

server:
  port: '9897'

rabbitmq:
  exchange:
    name: txt.device.control
    sensor:
      name: txt.sensor.data
  predict:
    routing:
      key: txt.predict
  bindings:
    - queueName: aircleanerQueue
      routingKey: aircleanerRouterKey
    - queueName: lightQueue
      routingKey: lightRouterKey
    - queueName: airconditionerQueue
      routingKey: airconditionerRouterKey
    - queueName: occupancyQueue
      routingKey: occupancyRouterKey
    - queueName: batteryQueue
      routingKey: batteryRouterKey
    - queueName: predictQueue
      routingKey: predictRouterKey
