name: Java CI/CD with Maven and Docker

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run SonarQube
        run: mvn sonar:sonar -Dsonar.projectKey=github-action -Dsonar.host.url=${{secrets.SONAR_HOST}} -Dsonar.login=${{secrets.SONAR_TOKEN}}

      - name: Build Docker image
        run: docker build -t txt-rule-engine .

      - name: Save Docker image to a tar file
        run: |
          sudo docker save -o rule-engine.tar txt-rule-engine
          sudo chmod 777 rule-engine.tar

      - name: Upload Docker image to cloud instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "rule-engine.tar"
          target: "~/rule-engine.tar"

      - name: SSH and deploy Docker container on cloud instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            sudo docker load -i ~/rule-engine.tar
            sudo docker stop rule-engine-container || true
            sudo docker rm rule-engine-container || true
            sudo docker run -d --name rule-engine-container -p 9897:9897 txt-rule-engine
